# Generated by Django 4.1.5 on 2023-01-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='User',
        ),
    ]
